# Generated by Django 3.0.1 on 2020-04-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_todolist_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='id',
            new_name='list_id',
        ),
    ]
