# Generated by Django 3.0.1 on 2020-04-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200407_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='list_id',
            new_name='id',
        ),
    ]
